# Generated by Django 4.2.7 on 2025-11-04 20:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('numero_login', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)], verbose_name='Número de Login')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('VENDEDOR', 'Vendedor'), ('SEPARADOR', 'Separador'), ('COMPRADORA', 'Compradora'), ('ADMINISTRADOR', 'Administrador')], max_length=20, verbose_name='Tipo')),
                ('pin_hash', models.CharField(max_length=128, verbose_name='PIN Hash')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True, verbose_name='Último Acesso')),
                ('tentativas_login', models.IntegerField(default=0, verbose_name='Tentativas de Login')),
                ('bloqueado_ate', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado Até')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['numero_login'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('criado_automaticamente', models.BooleanField(default=False, verbose_name='Criado Automaticamente')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orcamento', models.CharField(max_length=50, unique=True, verbose_name='Número do Orçamento')),
                ('codigo_cliente', models.CharField(max_length=100, verbose_name='Código do Cliente')),
                ('nome_cliente', models.CharField(max_length=200, verbose_name='Nome do Cliente')),
                ('data', models.DateField(verbose_name='Data')),
                ('logistica', models.CharField(blank=True, max_length=100, verbose_name='Logística')),
                ('embalagem', models.CharField(blank=True, max_length=100, verbose_name='Embalagem')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_SEPARACAO', 'Em Separação'), ('AGUARDANDO_COMPRA', 'Aguardando Compra'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Finalização')),
                ('deletado', models.BooleanField(default=False, verbose_name='Deletado')),
                ('deletado_em', models.DateTimeField(blank=True, null=True, verbose_name='Deletado Em')),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_deletados', to=settings.AUTH_USER_MODEL, verbose_name='Deletado Por')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=50, verbose_name='Ação')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('objeto_id', models.IntegerField(verbose_name='ID do Objeto')),
                ('dados_anteriores', models.JSONField(blank=True, null=True, verbose_name='Dados Anteriores')),
                ('dados_novos', models.JSONField(blank=True, null=True, verbose_name='Dados Novos')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Solicitada')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('separado', models.BooleanField(default=False, verbose_name='Separado')),
                ('separado_em', models.DateTimeField(blank=True, null=True, verbose_name='Separado Em')),
                ('em_compra', models.BooleanField(default=False, verbose_name='Em Compra')),
                ('marcado_compra_em', models.DateTimeField(blank=True, null=True, verbose_name='Marcado para Compra Em')),
                ('substituido', models.BooleanField(default=False, verbose_name='Substituído')),
                ('produto_substituto', models.CharField(blank=True, max_length=200, verbose_name='Produto Substituto')),
                ('compra_realizada', models.BooleanField(default=False, verbose_name='Compra Realizada')),
                ('compra_realizada_em', models.DateTimeField(blank=True, null=True, verbose_name='Compra Realizada Em')),
                ('compra_realizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Compra Realizada Por')),
                ('marcado_compra_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_marcados_compra', to=settings.AUTH_USER_MODEL, verbose_name='Marcado para Compra Por')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.pedido', verbose_name='Pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='core.produto', verbose_name='Produto')),
                ('separado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_separados', to=settings.AUTH_USER_MODEL, verbose_name='Separado Por')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Itens de Pedido',
                'ordering': ['id'],
            },
        ),
    ]
