# Generated by Django 4.2.7 on 2025-11-04 20:25

from django.db import migrations


def criar_usuario_admin(apps, schema_editor):
    """Cria o usuário administrador inicial"""
    Usuario = apps.get_model('core', 'Usuario')

    # Verifica se já existe um usuário com numero_login 1000
    if not Usuario.objects.filter(numero_login=1000).exists():
        # Importa o make_password para criar o hash do PIN
        from django.contrib.auth.hashers import make_password

        Usuario.objects.create(
            numero_login=1000,
            nome='Administrador',
            tipo='ADMINISTRADOR',
            pin_hash=make_password('1234'),
            ativo=True,
            is_staff=True,
            is_superuser=True,
            tentativas_login=0,
        )


def reverter_criacao_admin(apps, schema_editor):
    """Remove o usuário administrador inicial"""
    Usuario = apps.get_model('core', 'Usuario')
    Usuario.objects.filter(numero_login=1000).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(criar_usuario_admin, reverter_criacao_admin),
    ]
