# Generated by Django 4.2.7 on 2025-11-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_criar_usuario_admin_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='embalagem',
            field=models.CharField(blank=True, choices=[('CAIXA_PEQUENA', 'Caixa Pequena'), ('CAIXA_MEDIA', 'Caixa Média'), ('CAIXA_GRANDE', 'Caixa Grande'), ('SACO_PLASTICO', 'Saco Plástico'), ('SEM_EMBALAGEM', 'Sem Embalagem')], max_length=100, verbose_name='Embalagem'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='logistica',
            field=models.CharField(blank=True, choices=[('RETIRADA', 'Retirada'), ('ENTREGA', 'Entrega'), ('TRANSPORTADORA', 'Transportadora'), ('MOTOBOY', 'Motoboy')], max_length=100, verbose_name='Logística'),
        ),
    ]
