# Generated by Django 4.2.7 on 2025-11-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pedido_embalagem_alter_pedido_logistica'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empty_state_image', models.ImageField(blank=True, help_text='Imagem customizada para o estado vazio do dashboard (máx 2 MB, recomendado 512x512px)', null=True, upload_to='empty_state/', verbose_name='Imagem do Empty State')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
    ]
